"""Add reaction system tables

Revision ID: 8de8653b2595
Revises: 
Create Date: 2025-12-15 10:23:39.723290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de8653b2595'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('besitos_reward', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('besitos_reward >= 1', name='ck_besitos_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emoji', name='uq_reaction_emoji')
    )
    op.create_index(op.f('ix_reaction_configs_active'), 'reaction_configs', ['active'], unique=False)
    op.create_index(op.f('ix_reaction_configs_emoji'), 'reaction_configs', ['emoji'], unique=True)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('besitos_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', 'user_id', name='uq_message_user_reaction')
    )
    op.create_index(op.f('ix_message_reactions_channel_id'), 'message_reactions', ['channel_id'], unique=False)
    op.create_index('ix_message_reactions_lookup', 'message_reactions', ['channel_id', 'message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_index('ix_message_reactions_lookup', table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_channel_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_reaction_configs_emoji'), table_name='reaction_configs')
    op.drop_index(op.f('ix_reaction_configs_active'), table_name='reaction_configs')
    op.drop_table('reaction_configs')
    # ### end Alembic commands ###
